### ISSUE TITLE
Uncommmented line in compose file

### ISSUE THREAD

**Issue by banagale** [SeanRiggs/Huginn-Docker-Compose_AMD_X86_ARM#4]
**Describe the bug**
The current docker-compose file does not run due to a comment that is missing its comment hash (`#`)

**To Reproduce**
1. Clone the repo / wget the file
2. try running with  `docker-compose up -d`
4. See error: 

```
ERROR: yaml.scanner.ScannerError: while scanning a simple key
  in "./docker-compose.yaml", line 17, column 7
could not find expected ':'
  in "./docker-compose.yaml", line 18, column 5
```

**Expected behavior**
Orchestration startup is successful.

**Additional context**
Adding a # fixes it.

**Comment by SeanRiggs** [comment]
Thank you. Corrected error for missing # in line 17. Syntax now passes YAML Checker.
